---
version: "3.8"

services:

  tailscale:
    image: tailscale/tailscale:stable
    restart: unless-stopped
    container_name: tailscale
    network_mode: host
    hostname: nextcloud
    cap_add: # Required for tailscale to work
      - net_admin
      - net_raw
    environment:
      TS_EXTRA_ARGS: --qr
    volumes:
      - tailscale:/var/lib # State data will be stored in this directory
      - /dev/net/tun:/dev/net/tun # Required for tailscale to work

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mysql
    volumes:
      - nextcloud:/var/www/html

  mysql:
    image: mariadb:10.6
    container_name: mysql
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - mysql:/var/lib/mysql

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: unless-stopped
    ports:
      - 8081:80
    tmpfs:
      - /var/log/onlyoffice

volumes:
  tailscale:
  nextcloud:
  mysql:
  