---
version: "3.8"

services:

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    environment:
      CADDYFILE: |
        # Nextcloud reverse proxy
        cloud.cafio.co {
          reverse_proxy ${HOSTNAME}:8080
        }

        # OnlyOffice reverse proxy
        office.cafio.co {
          reverse_proxy ${HOSTNAME}:8081
        }
    command: sh -c 'printenv CADDYFILE > /config/Caddyfile && caddy run --config /config/Caddyfile --adapter caddyfile'
    volumes:
      - caddy:/data
      - caddy:/config

  # tailscale:
  #   image: tailscale/tailscale:stable
  #   restart: unless-stopped
  #   container_name: tailscale
  #   hostname: cloudserver
  #   privileged: true
  #   cap_add: # Required for tailscale to work
  #     - net_admin
  #     - sys_module
  #   command: tailscaled # docker exec tailscaled tailscale up --qr
  #   environment:
  #     TS_TAILSCALED_EXTRA_ARGS: --qr
  #   volumes:
  #     - tailscale:/var/lib # State data will be stored in this directory
  #     - /dev/net/tun:/dev/net/tun # Required for tailscale to work

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mysql
    volumes:
      - nextcloud:/var/www/html
      - ./ncdata:/var/www/html/data

  mysql:
    image: mariadb:10.6
    container_name: mysql
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - mysql:/var/lib/mysql

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: unless-stopped
    ports:
      - 8081:80
    tmpfs:
      - /var/log/onlyoffice
      - /var/www/onlyoffice/Data

volumes:
  caddy:
  tailscale:
  nexcloud:
  mysql: